export interface ParticipantData {
  id: number;
  artistPhoto: string;
  artistName: string;
  artistType: string;
  tags: string[];
  photos: string[];
}

export const participantsData: ParticipantData[] = [
  {
    id: 1,
    artistPhoto: "/artists/artist-photo-3.png",
    artistName: "Вадим Ігнатенко",
    artistType: "Скульптор · Художник",
    tags: ["Скульптури", "Картини", "Графіка", "Модернізм"],
    photos: [
      "/gallery/turquoise-blue_painting.png",
      "/gallery/autumn.png",
      "/gallery/big_lebovski.png",
      "/gallery/pulp_fiction.png",
      "/gallery/ship.png",
    ],
  },
  {
    id: 2,
    artistPhoto: "/artists/artist-photo-3.png",
    artistName: "Вадим Ігнатенко",
    artistType: "Скульптор · Художник",
    tags: ["Скульптури", "Картини", "Графіка", "Модернізм"],
    photos: [
      "/gallery/autumn.png",
      "/gallery/ship.png",
      "/gallery/turquoise-blue_painting.png",
      "/gallery/big_lebovski.png",
      "/gallery/pulp_fiction.png",
    ],
  },
  {
    id: 3,
    artistPhoto: "/artists/artist-photo-3.png",
    artistName: "Вадим Ігнатенко",
    artistType: "Скульптор · Художник",
    tags: ["Скульптури", "Картини", "Графіка", "Модернізм"],
    photos: [
      "/gallery/big_lebovski.png",
      "/gallery/pulp_fiction.png",
      "/gallery/autumn.png",
      "/gallery/ship.png",
      "/gallery/turquoise-blue_painting.png",
    ],
  },
  {
    id: 4,
    artistPhoto: "/artists/artist-photo-3.png",
    artistName: "Вадим Ігнатенко",
    artistType: "Скульптор · Художник",
    tags: ["Скульптури", "Картини", "Графіка", "Модернізм"],
    photos: [
      "/gallery/pulp_fiction.png",
      "/gallery/turquoise-blue_painting.png",
      "/gallery/ship.png",
      "/gallery/autumn.png",
      "/gallery/big_lebovski.png",
    ],
  },
  {
    id: 5,
    artistPhoto: "/artists/artist-photo-3.png",
    artistName: "Вадим Ігнатенко",
    artistType: "Скульптор · Художник",
    tags: ["Скульптури", "Картини", "Графіка", "Модернізм"],
    photos: [
      "/gallery/ship.png",
      "/gallery/big_lebovski.png",
      "/gallery/pulp_fiction.png",
      "/gallery/turquoise-blue_painting.png",
      "/gallery/autumn.png",
    ],
  },
  {
    id: 6,
    artistPhoto: "/artists/artist-photo-3.png",
    artistName: "Вадим Ігнатенко",
    artistType: "Скульптор · Художник",
    tags: ["Скульптури", "Картини", "Графіка", "Модернізм"],
    photos: [
      "/gallery/autumn.png",
      "/gallery/turquoise-blue_painting.png",
      "/gallery/big_lebovski.png",
      "/gallery/ship.png",
      "/gallery/pulp_fiction.png",
    ],
  },
  {
    id: 7,
    artistPhoto: "/artists/artist-photo-3.png",
    artistName: "Вадим Ігнатенко",
    artistType: "Скульптор · Художник",
    tags: ["Скульптури", "Картини", "Графіка", "Модернізм"],
    photos: [
      "/gallery/big_lebovski.png",
      "/gallery/ship.png",
      "/gallery/autumn.png",
      "/gallery/pulp_fiction.png",
      "/gallery/turquoise-blue_painting.png",
    ],
  },
  {
    id: 8,
    artistPhoto: "/artists/artist-photo-3.png",
    artistName: "Вадим Ігнатенко",
    artistType: "Скульптор · Художник",
    tags: ["Скульптури", "Картини", "Графіка", "Модернізм"],
    photos: [
      "/gallery/pulp_fiction.png",
      "/gallery/autumn.png",
      "/gallery/turquoise-blue_painting.png",
      "/gallery/big_lebovski.png",
      "/gallery/ship.png",
    ],
  },
  {
    id: 9,
    artistPhoto: "/artists/artist-photo-3.png",
    artistName: "Вадим Ігнатенко",
    artistType: "Скульптор · Художник",
    tags: ["Скульптури", "Картини", "Графіка", "Модернізм"],
    photos: [
      "/gallery/ship.png",
      "/gallery/pulp_fiction.png",
      "/gallery/big_lebovski.png",
      "/gallery/autumn.png",
      "/gallery/turquoise-blue_painting.png",
    ],
  },
  {
    id: 10,
    artistPhoto: "/artists/artist-photo-3.png",
    artistName: "Вадим Ігнатенко",
    artistType: "Скульптор · Художник",
    tags: ["Скульптури", "Картини", "Графіка", "Модернізм"],
    photos: [
      "/gallery/turquoise-blue_painting.png",
      "/gallery/big_lebovski.png",
      "/gallery/ship.png",
      "/gallery/pulp_fiction.png",
      "/gallery/autumn.png",
    ],
  },
  {
    id: 11,
    artistPhoto: "/artists/artist-photo-3.png",
    artistName: "Вадим Ігнатенко",
    artistType: "Скульптор · Художник",
    tags: ["Скульптури", "Картини", "Графіка", "Модернізм"],
    photos: [
      "/gallery/autumn.png",
      "/gallery/ship.png",
      "/gallery/pulp_fiction.png",
      "/gallery/turquoise-blue_painting.png",
      "/gallery/big_lebovski.png",
    ],
  },
  {
    id: 12,
    artistPhoto: "/artists/artist-photo-3.png",
    artistName: "Вадим Ігнатенко",
    artistType: "Скульптор · Художник",
    tags: ["Скульптури", "Картини", "Графіка", "Модернізм"],
    photos: [
      "/gallery/big_lebovski.png",
      "/gallery/autumn.png",
      "/gallery/turquoise-blue_painting.png",
      "/gallery/ship.png",
      "/gallery/pulp_fiction.png",
    ],
  },
  {
    id: 13,
    artistPhoto: "/artists/artist-photo-3.png",
    artistName: "Вадим Ігнатенко",
    artistType: "Скульптор · Художник",
    tags: ["Скульптури", "Картини", "Графіка", "Модернізм"],
    photos: [
      "/gallery/ship.png",
      "/gallery/turquoise-blue_painting.png",
      "/gallery/big_lebovski.png",
      "/gallery/autumn.png",
      "/gallery/pulp_fiction.png",
    ],
  },
  {
    id: 14,
    artistPhoto: "/artists/artist-photo-3.png",
    artistName: "Вадим Ігнатенко",
    artistType: "Скульптор · Художник",
    tags: ["Скульптури", "Картини", "Графіка", "Модернізм"],
    photos: [
      "/gallery/pulp_fiction.png",
      "/gallery/big_lebovski.png",
      "/gallery/autumn.png",
      "/gallery/ship.png",
      "/gallery/turquoise-blue_painting.png",
    ],
  },
  {
    id: 15,
    artistPhoto: "/artists/artist-photo-3.png",
    artistName: "Вадим Ігнатенко",
    artistType: "Скульптор · Художник",
    tags: ["Скульптури", "Картини", "Графіка", "Модернізм"],
    photos: [
      "/gallery/turquoise-blue_painting.png",
      "/gallery/ship.png",
      "/gallery/pulp_fiction.png",
      "/gallery/big_lebovski.png",
      "/gallery/autumn.png",
    ],
  },
];
